<div class="products">

  <?php foreach($this->products as $product): ?>
  <div class="product span4">

    <div class="image">
      <a href="/products/index/id/<?php echo $product['id']; ?>">
        <img alt="Armário de escritório ME4104 Bege Tecnomobili" src="//cdn.shopify.com/s/files/1/0710/9617/products/Tecnomobili-ArmC3A1rio-de-escritC3B3rio-ME4104-Branca-Tecnomobili-0302-215111-1-zoom_5969f510-6867-41d8-9903-5a785a250c45_large.jpg?v=1417273124">
      </a>
    </div>

    <div class="details">
      <a class="clearfix" href="/collections/frontpage/products/armario-de-escritorio-me4104-bege-tecnomobili">
        <h4 class="title"><?php echo $product['name']; ?></h4>

        <span class="price">
          R$ <?php echo number_format($product['price'], 2, ',', ' '); ?>
        </span>

      </a>
    </div>
  </div>
  <?php endforeach; ?>

</div>
