<div class="products">

  <?php foreach($this->products as $product): ?>
  <div class="product span4">

    <div class="image">
      <a href="/products/index/id/<?php echo $product['id']; ?>">
        <img alt="<?php echo $product['name']; ?>" src="<?php echo $product['img']; ?>">
      </a>
    </div>

    <div class="details">
      <a class="clearfix" href="/products/index/id/<?php echo $product['id']; ?>">
        <h4 class="title"><?php echo $product['name']; ?></h4>

        <span class="price">
          R$ <?php echo number_format($product['price'], 2, ',', ' '); ?>
        </span>

      </a>
    </div>
  </div>
  <?php endforeach; ?>

</div>
