<?php
$product = $this->product[0];
?>

<div class="row clearfix">


	<!-- Begin breadcrumb -->
	<div class="span12">
		<div class="breadcrumb clearfix">
			<span itemtype="http://data-vocabulary.org/Breadcrumb" itemscope=""><a itemprop="url" title="Furniture" href="/"><span itemprop="title">Home</span></a></span>
			<span class="arrow-space">&gt;</span>
			<strong><?php echo $product['name']; ?></strong>
		</div>
	</div>
	<!-- End breadcrumb -->


	<!-- Begin product photos -->
	<div class="span6">

		<!-- Begin featured image -->
		<div class="image featured">



			<a id="placeholder" class="zoom" href="<?php echo $product['img']; ?>">
				<img alt="<?php echo $product['name']; ?>" src="<?php echo $product['img']; ?>">
			</a>


		</div>
		<!-- End product image -->



	</div>
	<!-- End product photos -->



	<!-- Begin description -->
	<div class="span6">

		<h1 class="title"><?php echo $product['name']; ?></h1>

		<div class="purchase">
			<h2 id="price-preview" class="price">R$ <?php echo number_format($product['price'], 2, ',', ' '); ?></h2>
		</div>

		<form method="post" action="/cart/add">

			<!-- Begin product options -->
			<div class="product-options no-options ">

				<div class="purchase-section">
					<div class="purchase">

						<input type="hidden" name="id" value="<?php echo $product['id']; ?>">
						<input type="submit" value="Add to Cart" name="add" class="btn">

					</div>
				</div>
			</div>
			<!-- End product options -->

		</form>

		<div class="description">
			<meta charset="utf-8"><?php echo $product['description']; ?>
		</div>

	</div>
	<!-- End description -->
</div>
