<!doctype html>
<!--[if lt IE 7]><html class="no-js ie6 oldie" lang="en"><![endif]-->
<!--[if IE 7]><html class="no-js ie7 oldie" lang="en"><![endif]-->
<!--[if IE 8]><html class="no-js ie8 oldie" lang="en"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js" lang="en"><!--<![endif]-->
<head>



  <meta charset="utf-8" />
  <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1' /><![endif]-->

  <title>
    Best Online Furniture Store
  </title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <link rel="canonical" href="http://carrinho-de-compas.local/" />


  <link href="/assets/css/styles.scss.css?5" rel="stylesheet" type="text/css"  media="all"  />
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Cabin:300,400,700">
  <script src="/assets/js/html5shiv.js?5" type="text/javascript"></script>


  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
  <script src="/assets/js/jquery-migrate-1.2.0.min.js?5" type="text/javascript"></script>

  <script src="/assets/js/option_selection.js?96f59fd701c1ee18047ebc0ddd34014e81991510" type="text/javascript"></script>
  <script src="/assets/js/api.jquery.js?96f59fd701c1ee18047ebc0ddd34014e81991510" type="text/javascript"></script>


  <script src="/assets/js/scripts.js?5" type="text/javascript"></script>

</head>

<body>

  <!-- Begin toolbar -->
  <div class="toolbar-wrapper wrapper">
    <div class="toolbar span12 clearfix">
      <ul class="unstyled">


        <li class="search-field fl">
          <form class="search" action="/search">
            <input type="image" src="/assets/img/icon-search.png?5" alt="Go" id="go">
            <input type="text" name="q" class="search_box" placeholder="Search" value=""  />
          </form>
        </li>

        <li id="cart-target" class="toolbar-cart  <?php if($this->total_cart):?>has-items<?php endif;?>">
          <a href="/cart" class="cart" title="Shopping Cart">
            <span class="icon-cart"></span>
            <span id="cart-count"><?php echo $this->total_cart; ?></span>
            Cart
          </a>
        </li>


      </ul>
    </div>
  </div>
  <!-- End toolbar -->

  <!-- Begin wrapper -->
  <div id="transparency" class="wrapper clearfix">
    <div class="row p0">

      <!-- Begin navigation -->


      <div class="span12 clearfix">
        <div class="logo">

          <h1><a href="/">Furniture</a></h1>

        </div>
      </div>
      <section id="nav" class="row p30">
        <div class="span12">
          <nav class="main">
            <ul class="horizontal unstyled clearfix">


              <li>
                <a href="/" class=" current">
                  <span>Home</span></a>
                </li>



                <li>
                  <a href="/collections/all" class="">
                    <span>Catalog</span></a>
                  </li>


                    </ul>
                  </nav> <!-- /.main -->
                  <nav class="mobile clearfix">

                    <select name="main_navigation" id="main_navigation" class="fl">


                      <option value="/" selected="selected">Home</option>

                      <option value="/collections/all">Catalog</option>

                      <option value="/cart">Your cart (0)</option>
                    </select>
                  </nav> <!-- /.mobile -->
                </div>
              </section>


              <!-- End navigation -->

              <!-- Begin content-->
              <section id="content" class="clearfix">



                <!-- Start products -->


                <div class="clearfix helper-section">















                  <!-- Grid-style product -->
                  <div class="products">

                    <?php echo $this->layout()->content; ?>

                    <div style="clear:both;"></div>

                  </div>

                </div>

                <!-- End products -->

                <!-- start content page -->


                <!-- end content page -->


              </section>
              <!-- End content-->

            </div>
          </div>
          <!-- End wrapper -->

          <!-- Begin footer -->
          <div class="footer-wrapper wrapper">
            <footer>
              <div class="row">

                <div class="span12 full-border"></div>







                <!-- Begin latest blog post -->

                <div class="span4">

                  <div class="p30">
                    <h4>Latest News</h4>
                    <p class="p10"><strong><a href="/blogs/news/15942717-first-post" title="">First Post</a></strong></p>
                    <p>This is your store’s blog. You can use it to talk about new product launches, experiences, tips or other news you want your customers to read about. You can check...</p>
                  </div>
                </div>

                <!-- End latest blog post -->


                <!-- Begin footer navigation -->
                <div class="span4 footer-menu">
                  <h4>Quick Links</h4>
                  <ul class="unstyled">

                    <li><a href="/search" title="Search">Search</a></li>

                    <li><a href="/pages/about-us" title="About Us">About Us</a></li>

                  </ul>

                </div>
                <!-- End footer navigation -->





                <!-- Begin social -->
                <div class="span4">
                  <h4>Follow Us</h4>
                  <a href="http://twitter.com/shopify" title="Furniture on Twitter" class="icon-social twitter">Twitter</a>
                  <a href="http://facebook.com/shopify" title="Furniture on Facebook" class="icon-social facebook">Facebook</a>







                </div>
                <!-- End social -->


                <!-- Begin copyright -->
                <div class="span12 tc copyright">
                  <ul class="credit-cards p10 clearfix">
                    <li><img src="/assets/img/icon-cc-visa.png?5" alt="Visa" /></li>
                    <li><img src="/assets/img/icon-cc-mastercard.png?5" alt="MasterCard" /></li>
                    <li><img src="/assets/img/icon-cc-amex.png?5" alt="Amex" /></li>





                  </ul> <!-- /.credit-cards -->
                  <p>Copyright &copy; 2014 Furniture | <a href="http://www.shopify.com" target="_blank">Powered by Shopify</a></p>
                </div>
                <!-- End copyright -->

              </div>
            </footer>
          </div>
          <!-- End footer -->

          <script src="/assets/js/jquery.flexslider-min.js?5" type="text/javascript"></script>



          <script src="/assets/js/jquery.fancybox.js?5" type="text/javascript"></script>

        </body>
        </html>
